name: Docker Image Sync to Tencent Cloud

on:
  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Install yq
      run: |
        sudo apt-get update
        sudo apt-get install -y yq

    - name: Install Tencent Cloud CLI
      run: |
        curl -o /usr/local/bin/tcloud https://github.com/TencentCloud/tencentcloud-cli/releases/download/v0.0.1/tcloud-linux-amd64
        chmod +x /usr/local/bin/tcloud

    - name: Configure Tencent Cloud CLI
      run: |
        tcloud configure set secret-id ${{ secrets.TENCENTCLOUD_SECRET_ID }}
        tcloud configure set secret-key ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
        tcloud configure set region ap-guangzhou

    - name: Log in to Tencent Cloud Docker Registry
      run: |
        echo ${{ secrets.TENCENTCLOUD_PASSWORD }} | docker login -u ${{ secrets.TENCENTCLOUD_USERNAME }} --password-stdin ${{ secrets.TENCENTCLOUD_REGISTRY }}

    - name: Read Docker Images from YAML and Sync
      run: |
        IMAGES=$(yq e '.images[]' images.yaml)
        PRIVATE_REGISTRY="${{ secrets.TENCENTCLOUD_REGISTRY }}"
        for IMAGE in $IMAGES; do
          echo "Processing $IMAGE"
          docker pull $IMAGE
          docker tag $IMAGE $PRIVATE_REGISTRY/$IMAGE
          docker push $PRIVATE_REGISTRY/$IMAGE
        done
