name: Docker Image Sync to Tencent Cloud

on:
  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install yq
      run: |
        sudo apt-get update
        sudo apt-get install -y snapd
        sudo snap install yq

    - name: Install Python and Pip
      run: |
        sudo apt-get install -y python3 python3-pip

    - name: Install Tencent Cloud CLI
      run: |
        pip3 install tccli

    - name: Configure Tencent Cloud CLI
      run: |
        tccli configure set secretId ${{ secrets.TENCENTCLOUD_SECRET_ID }}
        tccli configure set secretKey ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
        tccli configure set region ap-guangzhou

    - name: Log in to Tencent Cloud Docker Registry
      run: |
        echo ${{ secrets.TENCENTCLOUD_PASSWORD }} | docker login -u ${{ secrets.TENCENTCLOUD_USERNAME }} --password-stdin ${{ secrets.TENCENTCLOUD_REGISTRY }}

    - name: Read Docker Images from YAML and Sync
      run: |
        IMAGES=$(yq e '.images[]' images.yaml)
        PRIVATE_REGISTRY="${{ secrets.TENCENTCLOUD_REGISTRY }}"
        for IMAGE in $IMAGES; do
          echo "Processing $IMAGE"
          docker pull $IMAGE
          docker tag $IMAGE $PRIVATE_REGISTRY/$IMAGE
          docker push $PRIVATE_REGISTRY/$IMAGE
        done
